# Generated by Django 6.1.1 on 2026-09-30 09:17

import deviceapi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_org_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(db_index=True, max_length=17)),
                ('secret_hash', models.CharField(max_length=64)),
                ('code', models.CharField(default=deviceapi.models.new_pair_code, max_length=6)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('local_ip', models.CharField(blank=True, max_length=45)),
                ('firmware', models.CharField(blank=True, max_length=32)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen'], name='deviceapi_d_last_se_b58fdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('hardware_id', 'secret_hash'), name='uniq_reader_secret')],
            },
        ),
    ]
