# Generated by Django 6.1.1 on 2026-09-17 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text='Short code used in invites', max_length=48, unique=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('term', models.CharField(default='2025/2026-1', help_text='Current academic term', max_length=16)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=48)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_devices', models.PositiveIntegerField(default=10)),
                ('max_students', models.PositiveIntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=128)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('roster_version', models.PositiveIntegerField(default=1)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('lecturer', 'Lecturer'), ('viewer', 'Viewer')], default='lecturer', max_length=12)),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('enroll_mode', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('firmware', models.CharField(blank=True, max_length=32)),
                ('queue_depth', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('short_name', models.CharField(blank=True, max_length=16)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], max_length=8)),
                ('tapped_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.classsession')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='TapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=16)),
                ('tapped_at', models.DateTimeField()),
                ('time_conf', models.CharField(default='synced', max_length=8)),
                ('client_id', models.BigIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='core.device')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('term', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.course')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetableslot'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.AddField(
            model_name='device',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.venue'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venue'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('lecturer', 'Lecturer'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('is_default', models.BooleanField(default=True, help_text='Org selected at login')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_default'], name='core_member_user_id_3fd146_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'org'), name='uniq_user_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uniq_course_per_org'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['org', '-created_at'], name='core_auditl_org_id_3ba7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['org', 'active'], name='core_studen_org_id_e14fc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('org', 'matric_no'), name='uniq_matric_per_org'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['org', 'course'], name='core_enroll_org_id_4d133d_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('org', 'student', 'course', 'term'), name='uniq_enrollment_per_org'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['org', 'uid', 'active'], name='core_card_org_id_4e1234_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('org', 'uid'), name='uniq_uid_per_org'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['org', 'student', 'session'], name='core_attend_org_id_055977_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_attendance'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['org', '-received_at'], name='core_tapeve_org_id_eeaf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['org', 'uid', '-received_at'], name='core_tapeve_org_id_159d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['org', 'outcome', '-received_at'], name='core_tapeve_org_id_488588_idx'),
        ),
        migrations.AddConstraint(
            model_name='tapevent',
            constraint=models.UniqueConstraint(fields=('device', 'client_id'), name='uniq_tap_per_device'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uniq_venue_per_org'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['org', 'venue', 'weekday', 'active'], name='core_timeta_org_id_deb532_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uniq_device_per_org'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['org', 'venue', 'starts_at'], name='core_classs_org_id_ef17ab_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['org', 'status', 'starts_at'], name='core_classs_org_id_575fce_idx'),
        ),
    ]
