# Generated by Django 6.1.1 on 2026-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapevent',
            name='device_outcome',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
