# Generated by Django 6.1.1 on 2026-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
